export const seededExercises = [
    {
        name: "Bench Press",
        description: "A barbell chest press performed lying on a bench.",
        instructions: "Lower the bar to your chest, then press it back up with control.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Incline Dumbbell Press",
        description: "An upper chest pressing movement using dumbbells.",
        instructions: "Press the dumbbells upward from an incline bench, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Push-Up",
        description: "A bodyweight pressing exercise.",
        instructions: "Lower your chest toward the floor, then push back up while keeping your body straight.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Pull-Up",
        description: "A bodyweight vertical pulling exercise.",
        instructions: "Pull your body upward until your chin clears the bar, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Lat Pulldown",
        description: "A machine-based vertical pulling exercise.",
        instructions: "Pull the bar down toward your upper chest, then return it slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Barbell Row",
        description: "A compound back exercise using a barbell.",
        instructions: "Pull the bar toward your torso while keeping your back flat, then lower it slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Shoulder Press",
        description: "An overhead pressing movement.",
        instructions: "Press the weight overhead, then lower it back to shoulder level.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Lateral Raise",
        description: "An isolation exercise for the shoulders.",
        instructions: "Raise the dumbbells out to your sides until shoulder height, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Barbell Curl",
        description: "A classic biceps exercise using a barbell.",
        instructions: "Curl the bar upward while keeping your elbows close to your sides, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "barbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hammer Curl",
        description: "A dumbbell curl variation with a neutral grip.",
        instructions: "Curl the dumbbells upward with palms facing inward, then lower under control.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Tricep Pushdown",
        description: "A cable or machine exercise for the triceps.",
        instructions: "Push the handle downward until your arms are straight, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Overhead Tricep Extension",
        description: "A triceps isolation movement performed overhead.",
        instructions: "Extend the weight upward from behind your head, then lower it carefully.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Back Squat",
        description: "A compound lower body exercise using a barbell.",
        instructions: "Lower into a squat with the bar on your back, then drive upward to standing.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Leg Press",
        description: "A machine-based lower body pressing exercise.",
        instructions: "Press the platform away with your feet, then lower it with control.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Romanian Deadlift",
        description: "A hip hinge exercise focused on the posterior chain.",
        instructions: "Hinge at the hips while lowering the weight, then return to standing by driving the hips forward.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["glutes", "back"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hip Thrust",
        description: "A glute-focused strength exercise.",
        instructions: "Drive your hips upward until fully extended, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Standing Calf Raise",
        description: "An isolation exercise for the calves.",
        instructions: "Rise onto your toes, squeeze at the top, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Plank",
        description: "An isometric core exercise.",
        instructions: "Hold a straight body position on your forearms and toes while bracing your core.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
];