export const seededExercises = [
    // CHEST
    {
        name: "Bench Press",
        description: "A barbell chest press performed lying on a bench.",
        instructions: "Lower the bar to your chest, then press it back up with control.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Incline Dumbbell Press",
        description: "An upper chest pressing movement using dumbbells.",
        instructions: "Press the dumbbells upward from an incline bench, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Push-Up",
        description: "A bodyweight pressing exercise.",
        instructions: "Lower your chest toward the floor, then push back up while keeping your body straight.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Bench Press",
        description: "A chest press performed with dumbbells on a flat bench.",
        instructions: "Press the dumbbells upward, then lower them slowly until your elbows are below shoulder level.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Incline Bench Press",
        description: "A barbell press that targets the upper chest.",
        instructions: "Lower the bar to your upper chest, then press it upward with control.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Decline Bench Press",
        description: "A barbell chest press performed on a decline bench.",
        instructions: "Lower the bar to your lower chest, then press it back up while keeping control.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Fly",
        description: "An isolation movement for the chest using dumbbells.",
        instructions: "Open your arms wide with a slight elbow bend, then bring the dumbbells together above your chest.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Machine Chest Press",
        description: "A machine-based pressing exercise for the chest.",
        instructions: "Push the handles forward until your arms are extended, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Chest Dip",
        description: "A bodyweight dip variation that emphasizes the chest.",
        instructions: "Lean slightly forward, lower your body with control, then press back up.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Close-Grip Push-Up",
        description: "A push-up variation that targets the chest and triceps.",
        instructions: "Place your hands closer than shoulder-width, lower your chest, then push back up.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders", "core"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // BACK
    {
        name: "Pull-Up",
        description: "A bodyweight vertical pulling exercise.",
        instructions: "Pull your body upward until your chin clears the bar, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Lat Pulldown",
        description: "A machine-based vertical pulling exercise.",
        instructions: "Pull the bar down toward your upper chest, then return it slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Barbell Row",
        description: "A compound back exercise using a barbell.",
        instructions: "Pull the bar toward your torso while keeping your back flat, then lower it slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Row",
        description: "A single-arm back exercise using a dumbbell.",
        instructions: "Pull the dumbbell toward your hip, squeeze your back, then lower it slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Seated Cable Row",
        description: "A machine-based horizontal pulling exercise.",
        instructions: "Pull the handle toward your torso while keeping your chest tall, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "T-Bar Row",
        description: "A heavy rowing movement for the upper and middle back.",
        instructions: "Pull the weight toward your chest while keeping your torso stable, then lower under control.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Chin-Up",
        description: "A bodyweight pulling exercise using an underhand grip.",
        instructions: "Pull your body upward until your chin clears the bar, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Straight-Arm Pulldown",
        description: "A machine exercise that targets the lats.",
        instructions: "Keep your arms mostly straight and pull the handle down toward your thighs.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["shoulders"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Inverted Row",
        description: "A bodyweight row performed under a bar.",
        instructions: "Pull your chest toward the bar while keeping your body straight, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "core"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // SHOULDERS
    {
        name: "Shoulder Press",
        description: "An overhead pressing movement.",
        instructions: "Press the weight overhead, then lower it back to shoulder level.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Lateral Raise",
        description: "An isolation exercise for the shoulders.",
        instructions: "Raise the dumbbells out to your sides until shoulder height, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Barbell Overhead Press",
        description: "A compound shoulder press using a barbell.",
        instructions: "Press the bar overhead from shoulder height, then lower it with control.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps", "core"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Arnold Press",
        description: "A dumbbell shoulder press variation with rotation.",
        instructions: "Start with palms facing you, rotate outward as you press overhead, then reverse the motion.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Front Raise",
        description: "An isolation movement for the front shoulders.",
        instructions: "Raise the dumbbells in front of you to shoulder height, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Rear Delt Fly",
        description: "An isolation exercise for the rear shoulders.",
        instructions: "Hinge forward and raise the dumbbells out to your sides, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["back"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Machine Shoulder Press",
        description: "A machine-based overhead pressing exercise.",
        instructions: "Press the handles overhead, then lower them back to shoulder height.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Upright Row",
        description: "A shoulder-focused pulling movement.",
        instructions: "Pull the weight upward toward your upper chest while keeping it close to your body.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["biceps"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // BICEPS
    {
        name: "Barbell Curl",
        description: "A classic biceps exercise using a barbell.",
        instructions: "Curl the bar upward while keeping your elbows close to your sides, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "barbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hammer Curl",
        description: "A dumbbell curl variation with a neutral grip.",
        instructions: "Curl the dumbbells upward with palms facing inward, then lower under control.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Curl",
        description: "A basic biceps curl using dumbbells.",
        instructions: "Curl the dumbbells upward while keeping your elbows still, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Incline Dumbbell Curl",
        description: "A biceps curl performed on an incline bench.",
        instructions: "Let your arms hang down, curl the dumbbells upward, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Preacher Curl",
        description: "A supported curl that isolates the biceps.",
        instructions: "Rest your arms on the pad, curl the weight upward, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Concentration Curl",
        description: "A single-arm biceps isolation exercise.",
        instructions: "Curl the dumbbell upward while keeping your upper arm steady against your thigh.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // TRICEPS
    {
        name: "Tricep Pushdown",
        description: "A cable or machine exercise for the triceps.",
        instructions: "Push the handle downward until your arms are straight, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Overhead Tricep Extension",
        description: "A triceps isolation movement performed overhead.",
        instructions: "Extend the weight upward from behind your head, then lower it carefully.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Skull Crusher",
        description: "A lying triceps extension using a barbell.",
        instructions: "Lower the bar toward your forehead by bending your elbows, then extend your arms.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Close-Grip Bench Press",
        description: "A bench press variation that emphasizes the triceps.",
        instructions: "Use a narrower grip, lower the bar to your chest, then press upward.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Bench Dip",
        description: "A bodyweight triceps exercise performed using a bench.",
        instructions: "Lower your body by bending your elbows, then push yourself back up.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["shoulders", "chest"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Tricep Kickback",
        description: "A dumbbell isolation movement for the triceps.",
        instructions: "Hinge forward, extend your arm backward, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // LEGS - QUADS
    {
        name: "Back Squat",
        description: "A compound lower body exercise using a barbell.",
        instructions: "Lower into a squat with the bar on your back, then drive upward to standing.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Leg Press",
        description: "A machine-based lower body pressing exercise.",
        instructions: "Press the platform away with your feet, then lower it with control.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Front Squat",
        description: "A squat variation with the bar held in front of the shoulders.",
        instructions: "Keep your chest tall, squat down, then drive back up through your feet.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "core"],
        equipment: "barbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Goblet Squat",
        description: "A beginner-friendly squat using a dumbbell.",
        instructions: "Hold the dumbbell at your chest, squat down, then stand back up.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "core"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Walking Lunge",
        description: "A lower body exercise performed by stepping forward into lunges.",
        instructions: "Step forward, lower your back knee toward the floor, then push into the next step.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Lunge",
        description: "A weighted lunge variation using dumbbells.",
        instructions: "Hold dumbbells at your sides, step forward into a lunge, then return to standing.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Bulgarian Split Squat",
        description: "A single-leg squat variation with the rear foot elevated.",
        instructions: "Place your rear foot on a bench, lower into a split squat, then drive back up.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "dumbbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Leg Extension",
        description: "A machine isolation exercise for the quads.",
        instructions: "Extend your legs until straight, squeeze your quads, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Step-Up",
        description: "A single-leg exercise performed by stepping onto an elevated surface.",
        instructions: "Step onto the platform, drive through your front foot, then step down with control.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // LEGS - HAMSTRINGS / GLUTES
    {
        name: "Romanian Deadlift",
        description: "A hip hinge exercise focused on the posterior chain.",
        instructions: "Hinge at the hips while lowering the weight, then return to standing by driving the hips forward.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["glutes", "back"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hip Thrust",
        description: "A glute-focused strength exercise.",
        instructions: "Drive your hips upward until fully extended, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Deadlift",
        description: "A full-body compound lift that emphasizes the posterior chain.",
        instructions: "Lift the bar from the floor by driving through your legs and extending your hips.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["glutes", "back", "core"],
        equipment: "barbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Romanian Deadlift",
        description: "A hip hinge exercise using dumbbells.",
        instructions: "Lower the dumbbells along your legs by hinging at the hips, then stand tall.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["glutes", "back"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Lying Leg Curl",
        description: "A machine isolation exercise for the hamstrings.",
        instructions: "Curl your heels toward your glutes, squeeze, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Seated Leg Curl",
        description: "A seated machine exercise for the hamstrings.",
        instructions: "Curl the pad down by bending your knees, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Glute Bridge",
        description: "A bodyweight exercise that targets the glutes.",
        instructions: "Lie on your back, drive your hips upward, squeeze your glutes, then lower.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Single-Leg Glute Bridge",
        description: "A single-leg glute bridge variation.",
        instructions: "Lift one leg, drive your hips upward using the planted foot, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cable Pull-Through",
        description: "A machine hip hinge exercise for the glutes and hamstrings.",
        instructions: "Hinge at your hips, let the handle move behind you, then drive your hips forward.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // CALVES
    {
        name: "Standing Calf Raise",
        description: "An isolation exercise for the calves.",
        instructions: "Rise onto your toes, squeeze at the top, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Seated Calf Raise",
        description: "A machine-based calf exercise performed seated.",
        instructions: "Raise your heels by pushing through your toes, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Calf Raise",
        description: "A weighted calf raise using dumbbells.",
        instructions: "Hold dumbbells at your sides, rise onto your toes, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Single-Leg Calf Raise",
        description: "A bodyweight calf raise performed on one leg.",
        instructions: "Stand on one foot, rise onto your toes, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: ["core"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // CORE
    {
        name: "Plank",
        description: "An isometric core exercise.",
        instructions: "Hold a straight body position on your forearms and toes while bracing your core.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Side Plank",
        description: "An isometric core exercise targeting the side of the torso.",
        instructions: "Support your body on one forearm and the side of your foot while keeping your hips lifted.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Crunch",
        description: "A basic abdominal exercise.",
        instructions: "Lift your shoulders off the floor by contracting your core, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Reverse Crunch",
        description: "A core exercise that emphasizes lower abdominal control.",
        instructions: "Bring your knees toward your chest, lift your hips slightly, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hanging Knee Raise",
        description: "A core exercise performed while hanging from a bar.",
        instructions: "Raise your knees toward your chest, then lower them slowly without swinging.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["forearms"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hanging Leg Raise",
        description: "An advanced core exercise performed while hanging.",
        instructions: "Raise your legs upward while keeping them controlled, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["forearms"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Russian Twist",
        description: "A rotational core exercise.",
        instructions: "Sit with your torso leaned back and rotate side to side with control.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Mountain Climber",
        description: "A dynamic bodyweight core exercise.",
        instructions: "From a push-up position, drive your knees toward your chest one at a time.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders", "quads"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dead Bug",
        description: "A beginner-friendly core stability exercise.",
        instructions: "Lie on your back, extend opposite arm and leg, then return and switch sides.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Bird Dog",
        description: "A core stability exercise performed on hands and knees.",
        instructions: "Extend opposite arm and leg while keeping your torso stable, then switch sides.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: ["glutes", "shoulders"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // FOREARMS
    {
        name: "Wrist Curl",
        description: "A forearm isolation exercise.",
        instructions: "Curl the dumbbells upward using only your wrists, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["forearms"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Reverse Wrist Curl",
        description: "A forearm exercise targeting wrist extensors.",
        instructions: "Hold dumbbells with palms down, raise your wrists upward, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["forearms"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Farmer Carry",
        description: "A loaded carry that builds grip and core strength.",
        instructions: "Hold heavy dumbbells at your sides and walk while keeping your posture tall.",
        exerciseType: "strength",
        primaryMuscles: ["forearms"],
        secondaryMuscles: ["core", "shoulders"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dead Hang",
        description: "A grip and shoulder stability exercise performed by hanging from a bar.",
        instructions: "Hang from a bar with straight arms while keeping your body controlled.",
        exerciseType: "mobility",
        primaryMuscles: ["forearms"],
        secondaryMuscles: ["shoulders", "back"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
];