export const seededExercises = [
    {
        name: "Assault Bike / Air Bike",
        description: "Full-body cardio on a fan-resistance bike using coordinated pedaling and pushing and pulling the handles. Suitable for continuous sessions or work/rest intervals.",
        instructions: "Adjust the seat so your knee stays slightly bent at the bottom of the pedal stroke. Keep your torso upright and core engaged. Pedal smoothly while pushing and pulling the handles in rhythm. Choose a sustainable pace for continuous cardio, or increase your effort during work intervals and ease off during recovery. Set your duration or rounds before starting.",
        exerciseType: "cardio",
        primaryMuscles: ["quads", "glutes"],
        secondaryMuscles: ["hamstrings", "calves", "chest", "back", "shoulders", "biceps", "triceps", "core"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Running / Treadmill",
        description: "Running outdoors or on a treadmill for continuous cardio or timed intervals. The legs provide propulsion while the core stabilizes the torso. The machine equipment category applies to the treadmill variation; outdoor running needs no machine.",
        instructions: "Begin at an easy walking or jogging pace. Run tall with relaxed shoulders and a natural arm swing, placing each foot near beneath your hips. Maintain a comfortable stride instead of reaching far forward. On a treadmill, attach the safety clip and adjust speed gradually. Set your duration or interval rounds, and optionally a target distance. Slow to a walk during recovery or when finishing.",
        exerciseType: "cardio",
        primaryMuscles: ["quads", "hamstrings", "glutes", "calves"],
        secondaryMuscles: ["core"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "SkiErg",
        description: "Standing ski-ergometer cardio using a coordinated double-pole movement. The core, back and triceps drive the downward pull, with the legs assisting. Suitable for continuous sessions or work/rest intervals.",
        instructions: "Stand with feet about shoulder-width apart and hold the handles above shoulder height with elbows slightly bent. Engage your core and drive the handles downward while hinging at the hips and bending your knees slightly. Finish with the handles beside your thighs. Return smoothly to standing and raise your arms for the next stroke. Keep the motion controlled rather than pulling only with your arms. Set your duration or interval rounds before starting.",
        exerciseType: "cardio",
        primaryMuscles: ["core", "back", "triceps"],
        secondaryMuscles: ["shoulders", "quads", "glutes", "hamstrings", "calves", "forearms"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Custom Cardio Activity",
        description: "A generic timer for a cardio activity of your choice, using continuous duration or work/rest intervals. Muscle groups and equipment depend on the actual movement and are intentionally unspecified. Create a custom exercise for activity-specific muscle groups and equipment.",
        instructions: "Choose your activity and use its appropriate equipment and technique. Configure a continuous duration or the number of rounds, work time and rest time before starting. For intervals, perform the activity during work periods and recover during rest periods. Pause when needed and save your completion when finished.",
        exerciseType: "cardio",
        primaryMuscles: [],
        secondaryMuscles: [],
        equipment: undefined,
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    // CHEST
    {
        name: "Bench Press",
        description: "A barbell chest press performed lying on a bench.",
        instructions: "Lower the bar to your chest, then press it back up with control.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Incline Dumbbell Press",
        description: "An upper chest pressing movement using dumbbells.",
        instructions: "Press the dumbbells upward from an incline bench, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Push-Up",
        description: "A bodyweight pressing exercise.",
        instructions: "Lower your chest toward the floor, then push back up while keeping your body straight.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Bench Press",
        description: "A chest press performed with dumbbells on a flat bench.",
        instructions: "Press the dumbbells upward, then lower them slowly until your elbows are below shoulder level.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Incline Bench Press",
        description: "A barbell press that targets the upper chest.",
        instructions: "Lower the bar to your upper chest, then press it upward with control.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Decline Bench Press",
        description: "A barbell chest press performed on a decline bench.",
        instructions: "Lower the bar to your lower chest, then press it back up while keeping control.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Fly",
        description: "An isolation movement for the chest using dumbbells.",
        instructions: "Open your arms wide with a slight elbow bend, then bring the dumbbells together above your chest.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Machine Chest Press",
        description: "A machine-based pressing exercise for the chest.",
        instructions: "Push the handles forward until your arms are extended, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Chest Dip",
        description: "A bodyweight dip variation that emphasizes the chest.",
        instructions: "Lean slightly forward, lower your body with control, then press back up.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Close-Grip Push-Up",
        description: "A push-up variation that targets the chest and triceps.",
        instructions: "Place your hands closer than shoulder-width, lower your chest, then push back up.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders", "core"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // BACK
    {
        name: "Pull-Up",
        description: "A bodyweight vertical pulling exercise.",
        instructions: "Pull your body upward until your chin clears the bar, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Lat Pulldown",
        description: "A machine-based vertical pulling exercise.",
        instructions: "Pull the bar down toward your upper chest, then return it slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Barbell Row",
        description: "A compound back exercise using a barbell.",
        instructions: "Pull the bar toward your torso while keeping your back flat, then lower it slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Row",
        description: "A single-arm back exercise using a dumbbell.",
        instructions: "Pull the dumbbell toward your hip, squeeze your back, then lower it slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Seated Cable Row",
        description: "A machine-based horizontal pulling exercise.",
        instructions: "Pull the handle toward your torso while keeping your chest tall, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "T-Bar Row",
        description: "A heavy rowing movement for the upper and middle back.",
        instructions: "Pull the weight toward your chest while keeping your torso stable, then lower under control.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Chin-Up",
        description: "A bodyweight pulling exercise using an underhand grip.",
        instructions: "Pull your body upward until your chin clears the bar, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Straight-Arm Pulldown",
        description: "A machine exercise that targets the lats.",
        instructions: "Keep your arms mostly straight and pull the handle down toward your thighs.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["shoulders"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Inverted Row",
        description: "A bodyweight row performed under a bar.",
        instructions: "Pull your chest toward the bar while keeping your body straight, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "core"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // SHOULDERS
    {
        name: "Shoulder Press",
        description: "An overhead pressing movement.",
        instructions: "Press the weight overhead, then lower it back to shoulder level.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Lateral Raise",
        description: "An isolation exercise for the shoulders.",
        instructions: "Raise the dumbbells out to your sides until shoulder height, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Barbell Overhead Press",
        description: "A compound shoulder press using a barbell.",
        instructions: "Press the bar overhead from shoulder height, then lower it with control.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps", "core"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Arnold Press",
        description: "A dumbbell shoulder press variation with rotation.",
        instructions: "Start with palms facing you, rotate outward as you press overhead, then reverse the motion.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Front Raise",
        description: "An isolation movement for the front shoulders.",
        instructions: "Raise the dumbbells in front of you to shoulder height, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Rear Delt Fly",
        description: "An isolation exercise for the rear shoulders.",
        instructions: "Hinge forward and raise the dumbbells out to your sides, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["back"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Machine Shoulder Press",
        description: "A machine-based overhead pressing exercise.",
        instructions: "Press the handles overhead, then lower them back to shoulder height.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Upright Row",
        description: "A shoulder-focused pulling movement.",
        instructions: "Pull the weight upward toward your upper chest while keeping it close to your body.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["biceps"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // BICEPS
    {
        name: "Barbell Curl",
        description: "A classic biceps exercise using a barbell.",
        instructions: "Curl the bar upward while keeping your elbows close to your sides, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "barbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hammer Curl",
        description: "A dumbbell curl variation with a neutral grip.",
        instructions: "Curl the dumbbells upward with palms facing inward, then lower under control.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Curl",
        description: "A basic biceps curl using dumbbells.",
        instructions: "Curl the dumbbells upward while keeping your elbows still, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Incline Dumbbell Curl",
        description: "A biceps curl performed on an incline bench.",
        instructions: "Let your arms hang down, curl the dumbbells upward, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Preacher Curl",
        description: "A supported curl that isolates the biceps.",
        instructions: "Rest your arms on the pad, curl the weight upward, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Concentration Curl",
        description: "A single-arm biceps isolation exercise.",
        instructions: "Curl the dumbbell upward while keeping your upper arm steady against your thigh.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // TRICEPS
    {
        name: "Tricep Pushdown",
        description: "A cable or machine exercise for the triceps.",
        instructions: "Push the handle downward until your arms are straight, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Overhead Tricep Extension",
        description: "A triceps isolation movement performed overhead.",
        instructions: "Extend the weight upward from behind your head, then lower it carefully.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Skull Crusher",
        description: "A lying triceps extension using a barbell.",
        instructions: "Lower the bar toward your forehead by bending your elbows, then extend your arms.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Close-Grip Bench Press",
        description: "A bench press variation that emphasizes the triceps.",
        instructions: "Use a narrower grip, lower the bar to your chest, then press upward.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Bench Dip",
        description: "A bodyweight triceps exercise performed using a bench.",
        instructions: "Lower your body by bending your elbows, then push yourself back up.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["shoulders", "chest"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Tricep Kickback",
        description: "A dumbbell isolation movement for the triceps.",
        instructions: "Hinge forward, extend your arm backward, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // LEGS - QUADS
    {
        name: "Back Squat",
        description: "A compound lower body exercise using a barbell.",
        instructions: "Lower into a squat with the bar on your back, then drive upward to standing.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Leg Press",
        description: "A machine-based lower body pressing exercise.",
        instructions: "Press the platform away with your feet, then lower it with control.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Front Squat",
        description: "A squat variation with the bar held in front of the shoulders.",
        instructions: "Keep your chest tall, squat down, then drive back up through your feet.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "core"],
        equipment: "barbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Goblet Squat",
        description: "A beginner-friendly squat using a dumbbell.",
        instructions: "Hold the dumbbell at your chest, squat down, then stand back up.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "core"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Walking Lunge",
        description: "A lower body exercise performed by stepping forward into lunges.",
        instructions: "Step forward, lower your back knee toward the floor, then push into the next step.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Lunge",
        description: "A weighted lunge variation using dumbbells.",
        instructions: "Hold dumbbells at your sides, step forward into a lunge, then return to standing.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Bulgarian Split Squat",
        description: "A single-leg squat variation with the rear foot elevated.",
        instructions: "Place your rear foot on a bench, lower into a split squat, then drive back up.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "dumbbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Leg Extension",
        description: "A machine isolation exercise for the quads.",
        instructions: "Extend your legs until straight, squeeze your quads, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Step-Up",
        description: "A single-leg exercise performed by stepping onto an elevated surface.",
        instructions: "Step onto the platform, drive through your front foot, then step down with control.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // LEGS - HAMSTRINGS / GLUTES
    {
        name: "Romanian Deadlift",
        description: "A hip hinge exercise focused on the posterior chain.",
        instructions: "Hinge at the hips while lowering the weight, then return to standing by driving the hips forward.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["glutes", "back"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hip Thrust",
        description: "A glute-focused strength exercise.",
        instructions: "Drive your hips upward until fully extended, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Deadlift",
        description: "A full-body compound lift that emphasizes the posterior chain.",
        instructions: "Lift the bar from the floor by driving through your legs and extending your hips.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["glutes", "back", "core"],
        equipment: "barbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Romanian Deadlift",
        description: "A hip hinge exercise using dumbbells.",
        instructions: "Lower the dumbbells along your legs by hinging at the hips, then stand tall.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["glutes", "back"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Lying Leg Curl",
        description: "A machine isolation exercise for the hamstrings.",
        instructions: "Curl your heels toward your glutes, squeeze, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Seated Leg Curl",
        description: "A seated machine exercise for the hamstrings.",
        instructions: "Curl the pad down by bending your knees, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Glute Bridge",
        description: "A bodyweight exercise that targets the glutes.",
        instructions: "Lie on your back, drive your hips upward, squeeze your glutes, then lower.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Single-Leg Glute Bridge",
        description: "A single-leg glute bridge variation.",
        instructions: "Lift one leg, drive your hips upward using the planted foot, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cable Pull-Through",
        description: "A machine hip hinge exercise for the glutes and hamstrings.",
        instructions: "Hinge at your hips, let the handle move behind you, then drive your hips forward.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // CALVES
    {
        name: "Standing Calf Raise",
        description: "An isolation exercise for the calves.",
        instructions: "Rise onto your toes, squeeze at the top, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Seated Calf Raise",
        description: "A machine-based calf exercise performed seated.",
        instructions: "Raise your heels by pushing through your toes, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Calf Raise",
        description: "A weighted calf raise using dumbbells.",
        instructions: "Hold dumbbells at your sides, rise onto your toes, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Single-Leg Calf Raise",
        description: "A bodyweight calf raise performed on one leg.",
        instructions: "Stand on one foot, rise onto your toes, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: ["core"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // CORE
    {
        name: "Plank",
        description: "An isometric core exercise.",
        instructions: "Hold a straight body position on your forearms and toes while bracing your core.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Side Plank",
        description: "An isometric core exercise targeting the side of the torso.",
        instructions: "Support your body on one forearm and the side of your foot while keeping your hips lifted.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Crunch",
        description: "A basic abdominal exercise.",
        instructions: "Lift your shoulders off the floor by contracting your core, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Reverse Crunch",
        description: "A core exercise that emphasizes lower abdominal control.",
        instructions: "Bring your knees toward your chest, lift your hips slightly, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hanging Knee Raise",
        description: "A core exercise performed while hanging from a bar.",
        instructions: "Raise your knees toward your chest, then lower them slowly without swinging.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["forearms"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hanging Leg Raise",
        description: "An advanced core exercise performed while hanging.",
        instructions: "Raise your legs upward while keeping them controlled, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["forearms"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Russian Twist",
        description: "A rotational core exercise.",
        instructions: "Sit with your torso leaned back and rotate side to side with control.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Mountain Climber",
        description: "A dynamic bodyweight core exercise.",
        instructions: "From a push-up position, drive your knees toward your chest one at a time.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders", "quads"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dead Bug",
        description: "A beginner-friendly core stability exercise.",
        instructions: "Lie on your back, extend opposite arm and leg, then return and switch sides.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Bird Dog",
        description: "A core stability exercise performed on hands and knees.",
        instructions: "Extend opposite arm and leg while keeping your torso stable, then switch sides.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: ["glutes", "shoulders"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // FOREARMS
    {
        name: "Wrist Curl",
        description: "A forearm isolation exercise.",
        instructions: "Curl the dumbbells upward using only your wrists, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["forearms"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Reverse Wrist Curl",
        description: "A forearm exercise targeting wrist extensors.",
        instructions: "Hold dumbbells with palms down, raise your wrists upward, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["forearms"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Farmer Carry",
        description: "A loaded carry that builds grip and core strength.",
        instructions: "Hold heavy dumbbells at your sides and walk while keeping your posture tall.",
        exerciseType: "strength",
        primaryMuscles: ["forearms"],
        secondaryMuscles: ["core", "shoulders"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dead Hang",
        description: "A grip and shoulder stability exercise performed by hanging from a bar.",
        instructions: "Hang from a bar with straight arms while keeping your body controlled.",
        exerciseType: "mobility",
        primaryMuscles: ["forearms"],
        secondaryMuscles: ["shoulders", "back"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },

    // EXPANDED EXERCISES
    {
        name: "Incline Push-Up",
        description: "A push-up variation with the hands elevated to make the movement easier.",
        instructions: "Place your hands on a bench or box, lower your chest with control, then push back up.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Decline Push-Up",
        description: "A push-up variation with the feet elevated to increase upper chest and shoulder demand.",
        instructions: "Place your feet on a bench, keep your body straight, lower your chest, then press back up.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps", "core"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cable Chest Fly",
        description: "A cable isolation exercise for the chest.",
        instructions: "Stand between the cables, bring your hands together in front of your chest, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Pec Deck Fly",
        description: "A machine chest fly that isolates the pecs.",
        instructions: "Press the pads together in front of your chest, squeeze, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Pullover",
        description: "A dumbbell movement that trains the chest and upper back through a long range of motion.",
        instructions: "Lie on a bench, lower the dumbbell behind your head, then pull it back over your chest.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["back", "shoulders"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Barbell Floor Press",
        description: "A barbell press performed lying on the floor.",
        instructions: "Lower the bar until your upper arms touch the floor, then press it back up.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Floor Press",
        description: "A dumbbell press performed lying on the floor.",
        instructions: "Lower the dumbbells until your upper arms touch the floor, then press upward.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Svend Press",
        description: "A plate squeeze press that emphasizes chest contraction.",
        instructions: "Press a plate or dumbbell forward while squeezing your hands together, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Single-Arm Dumbbell Bench Press",
        description: "A unilateral dumbbell chest press that challenges core stability.",
        instructions: "Press one dumbbell at a time while keeping your torso stable on the bench.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders", "core"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Machine Incline Chest Press",
        description: "A machine press variation that targets the upper chest.",
        instructions: "Press the handles upward and forward, then lower back to the start with control.",
        exerciseType: "strength",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Chest-Supported Dumbbell Row",
        description: "A dumbbell row performed with the chest supported on an incline bench.",
        instructions: "Pull the dumbbells toward your ribs, squeeze your back, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Machine Row",
        description: "A machine-based horizontal pulling exercise for the back.",
        instructions: "Pull the handles toward your torso, squeeze your back, then return with control.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Wide-Grip Lat Pulldown",
        description: "A lat pulldown variation using a wider grip.",
        instructions: "Pull the bar toward your upper chest while keeping your chest tall, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Close-Grip Lat Pulldown",
        description: "A lat pulldown variation using a close grip handle.",
        instructions: "Pull the handle toward your upper chest, squeeze your lats, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "One-Arm Cable Row",
        description: "A single-arm cable row for the back.",
        instructions: "Pull the handle toward your hip, keep your torso stable, then return with control.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "core"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Pendlay Row",
        description: "A strict barbell row starting from the floor each rep.",
        instructions: "Pull the bar from the floor to your torso, then return it to the floor under control.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "core"],
        equipment: "barbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Rack Pull",
        description: "A partial deadlift variation that emphasizes the back and posterior chain.",
        instructions: "Set the bar on pins, pull to standing, then lower back to the rack with control.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["glutes", "hamstrings", "forearms"],
        equipment: "barbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Meadows Row",
        description: "A landmine-style single-arm row for the upper back and lats.",
        instructions: "Hinge at the hips, pull the bar toward your hip, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps", "shoulders"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Renegade Row",
        description: "A plank row using dumbbells that trains the back and core.",
        instructions: "Hold a push-up position, row one dumbbell toward your ribs, then switch sides.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["core", "biceps", "shoulders"],
        equipment: "dumbbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Band Row",
        description: "A rowing exercise using a resistance band.",
        instructions: "Anchor the band, pull your elbows back, squeeze your shoulder blades, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["back"],
        secondaryMuscles: ["biceps"],
        equipment: "band",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Seated Dumbbell Shoulder Press",
        description: "An overhead press performed seated with dumbbells.",
        instructions: "Press the dumbbells overhead from shoulder height, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cable Lateral Raise",
        description: "A cable isolation exercise for the side delts.",
        instructions: "Raise the cable handle out to your side until shoulder height, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Machine Lateral Raise",
        description: "A machine exercise for the side shoulders.",
        instructions: "Raise the pads outward until shoulder height, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Reverse Pec Deck",
        description: "A machine exercise for the rear shoulders and upper back.",
        instructions: "Push the handles backward by opening your arms, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["back"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Push Press",
        description: "An explosive overhead press using leg drive.",
        instructions: "Dip slightly, drive through your legs, press the bar overhead, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps", "quads", "core"],
        equipment: "barbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Landmine Press",
        description: "An angled pressing exercise using a barbell in a landmine setup.",
        instructions: "Press the bar upward and forward, then lower it back to shoulder height.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["chest", "triceps", "core"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Shrug",
        description: "A trap-focused shoulder movement using dumbbells.",
        instructions: "Hold dumbbells at your sides, shrug your shoulders upward, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Barbell Shrug",
        description: "A heavy shrug variation using a barbell.",
        instructions: "Hold the bar, shrug your shoulders upward, pause briefly, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["forearms"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Band Pull-Apart",
        description: "A band exercise for rear shoulders and upper back.",
        instructions: "Hold a band in front of you, pull it apart until it reaches your chest, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["back"],
        equipment: "band",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Face Pull",
        description: "A cable exercise for rear delts and upper back.",
        instructions: "Pull the rope toward your face with elbows high, then return with control.",
        exerciseType: "strength",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["back"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cable Curl",
        description: "A cable biceps curl with constant tension.",
        instructions: "Curl the handle upward while keeping your elbows still, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "EZ-Bar Curl",
        description: "A barbell curl variation using an angled grip.",
        instructions: "Curl the bar upward while keeping your elbows close to your sides, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "barbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Spider Curl",
        description: "A supported curl performed chest-down on an incline bench.",
        instructions: "Curl the dumbbells upward while your upper arms hang down, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Reverse Curl",
        description: "A curl variation using an overhand grip.",
        instructions: "Curl the weight upward with palms facing down, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Zottman Curl",
        description: "A curl variation that trains the biceps and forearms.",
        instructions: "Curl up with palms up, rotate palms down at the top, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Machine Curl",
        description: "A machine-based biceps isolation exercise.",
        instructions: "Curl the handles upward, squeeze your biceps, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Band Curl",
        description: "A resistance band curl for the biceps.",
        instructions: "Stand on the band, curl your hands toward your shoulders, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "band",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cross-Body Hammer Curl",
        description: "A hammer curl variation performed across the body.",
        instructions: "Curl one dumbbell toward the opposite shoulder, then lower and switch sides.",
        exerciseType: "strength",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Rope Tricep Pushdown",
        description: "A triceps pushdown using a rope attachment.",
        instructions: "Push the rope down, separate the ends slightly at the bottom, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Single-Arm Cable Pushdown",
        description: "A unilateral triceps pushdown.",
        instructions: "Push the handle down with one arm until extended, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cable Overhead Tricep Extension",
        description: "An overhead triceps extension using a cable.",
        instructions: "Face away from the cable, extend your arms overhead, then bend your elbows with control.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Skull Crusher",
        description: "A lying triceps extension using dumbbells.",
        instructions: "Lower the dumbbells toward your head by bending your elbows, then extend your arms.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "EZ-Bar Skull Crusher",
        description: "A skull crusher variation using an angled bar.",
        instructions: "Lower the bar toward your forehead, then extend your elbows to lift it back up.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Diamond Push-Up",
        description: "A close-hand push-up variation that emphasizes the triceps.",
        instructions: "Place your hands close together, lower your chest, then push back up.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "shoulders", "core"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Assisted Dip",
        description: "A machine-assisted dip variation for chest and triceps.",
        instructions: "Use assistance to lower into a dip, then press back up with control.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "shoulders"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Machine Tricep Extension",
        description: "A machine-based triceps isolation movement.",
        instructions: "Extend your elbows against the pads or handles, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hack Squat",
        description: "A machine squat variation that emphasizes the quads.",
        instructions: "Lower the sled under control, then press back up through your feet.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings"],
        equipment: "machine",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Smith Machine Squat",
        description: "A squat variation performed on a Smith machine.",
        instructions: "Place the bar across your upper back, squat down, then drive back up.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Split Squat",
        description: "A stationary lunge variation for the legs.",
        instructions: "Lower into a split stance until your back knee approaches the floor, then stand back up.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Reverse Lunge",
        description: "A lunge variation where you step backward.",
        instructions: "Step back, lower your back knee, then push through the front foot to return.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Box Squat",
        description: "A squat variation where you sit back to a box or bench.",
        instructions: "Squat to the box with control, pause briefly, then stand back up.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Sissy Squat",
        description: "A bodyweight quad-focused squat variation.",
        instructions: "Keep your hips extended, bend your knees forward, then return to standing with control.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["core"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Pistol Squat",
        description: "A single-leg squat performed with the free leg extended.",
        instructions: "Lower on one leg while keeping control, then stand back up.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "core"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Wall Sit",
        description: "An isometric quad exercise performed against a wall.",
        instructions: "Slide down the wall until your knees are bent and hold the position.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "core"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cyclist Squat",
        description: "A squat variation with heels elevated to emphasize the quads.",
        instructions: "Elevate your heels, squat down with control, then drive back up.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "core"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Smith Machine Lunge",
        description: "A lunge performed with a Smith machine bar.",
        instructions: "Step into a split stance, lower down, then press back up through the front foot.",
        exerciseType: "strength",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings"],
        equipment: "machine",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Good Morning",
        description: "A barbell hip hinge that trains the posterior chain.",
        instructions: "With the bar on your back, hinge at your hips, then return to standing.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["glutes", "back", "core"],
        equipment: "barbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Nordic Hamstring Curl",
        description: "A bodyweight hamstring exercise focused on eccentric strength.",
        instructions: "Anchor your feet, lower your torso slowly, then assist yourself back up if needed.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["glutes", "core"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Single-Leg Romanian Deadlift",
        description: "A unilateral hip hinge for hamstrings and glutes.",
        instructions: "Hinge forward on one leg while lowering the weight, then return to standing.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["glutes", "core"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Kettlebell Swing",
        description: "A dynamic hip hinge exercise using a kettlebell.",
        instructions: "Hinge at the hips, swing the kettlebell forward with hip drive, then let it return under control.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core", "back"],
        equipment: "kettlebell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Sumo Deadlift",
        description: "A wide-stance deadlift variation.",
        instructions: "Set your feet wide, grip the bar inside your legs, then stand by extending hips and knees.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "quads", "back", "core"],
        equipment: "barbell",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Trap Bar Deadlift",
        description: "A deadlift variation using a trap bar.",
        instructions: "Stand inside the bar, drive through your feet, stand tall, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "quads", "back", "core"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Machine Hip Abduction",
        description: "A machine exercise for the glutes.",
        instructions: "Push your knees outward against the pads, squeeze, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cable Glute Kickback",
        description: "A cable exercise that isolates the glutes.",
        instructions: "Kick one leg backward against the cable, squeeze your glute, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Frog Pump",
        description: "A bodyweight glute bridge variation with feet together.",
        instructions: "Press your hips upward while keeping the soles of your feet together, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Banded Glute Bridge",
        description: "A glute bridge performed with a resistance band around the knees.",
        instructions: "Drive your hips upward while pushing your knees slightly outward against the band.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core"],
        equipment: "band",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Smith Machine Hip Thrust",
        description: "A hip thrust performed using a Smith machine.",
        instructions: "Position your upper back on a bench, drive your hips upward, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "core"],
        equipment: "machine",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Standing Cable Leg Curl",
        description: "A cable hamstring curl performed standing.",
        instructions: "Attach the cable to one ankle, curl your heel toward your glutes, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Leg Press Calf Raise",
        description: "A calf raise performed on the leg press machine.",
        instructions: "Press through your toes to raise the sled, then lower your heels slowly.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Donkey Calf Raise",
        description: "A calf raise variation with the hips hinged forward.",
        instructions: "Rise onto your toes, squeeze your calves, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Smith Machine Calf Raise",
        description: "A standing calf raise using a Smith machine.",
        instructions: "Place the bar across your upper back, rise onto your toes, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Calf Press Machine",
        description: "A machine-based calf press movement.",
        instructions: "Press through your toes against the platform, pause, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Tibialis Raise",
        description: "An exercise for the front lower leg.",
        instructions: "Lean against a wall, lift your toes toward your shins, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Jump Rope",
        description: "A conditioning exercise that also trains the calves.",
        instructions: "Jump rhythmically over the rope while staying light on your feet.",
        exerciseType: "cardio",
        primaryMuscles: ["calves"],
        secondaryMuscles: ["core", "shoulders"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Ab Wheel Rollout",
        description: "A challenging core anti-extension exercise.",
        instructions: "Roll the wheel forward while bracing your core, then pull back to the start.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cable Crunch",
        description: "A weighted crunch using a cable machine.",
        instructions: "Kneel under the cable, crunch your ribs toward your hips, then return slowly.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Pallof Press",
        description: "An anti-rotation core exercise using a cable or band.",
        instructions: "Press the handle straight out from your chest while resisting rotation, then return.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Band Pallof Press",
        description: "A band-based anti-rotation core exercise.",
        instructions: "Anchor the band, press it straight out from your chest, then return with control.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders"],
        equipment: "band",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Bicycle Crunch",
        description: "A rotational abdominal exercise.",
        instructions: "Bring one elbow toward the opposite knee while extending the other leg, then switch sides.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "V-Up",
        description: "A bodyweight core exercise where hands and feet meet above the torso.",
        instructions: "Lift your legs and torso at the same time, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hollow Body Hold",
        description: "An isometric core exercise.",
        instructions: "Lie on your back, lift shoulders and legs slightly, and hold a braced position.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Toe Touch Crunch",
        description: "A crunch variation reaching toward the toes.",
        instructions: "Lift your shoulders and reach toward your toes, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cable Woodchop",
        description: "A rotational cable core exercise.",
        instructions: "Pull the cable diagonally across your body while rotating through your torso.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders"],
        equipment: "machine",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "L-Sit",
        description: "An advanced isometric core hold.",
        instructions: "Support your body with your hands and hold your legs straight out in front of you.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Flutter Kick",
        description: "A bodyweight core exercise using alternating leg kicks.",
        instructions: "Lie on your back, brace your core, and alternate small controlled leg kicks.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: [],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Bear Crawl",
        description: "A crawling movement that trains core stability and shoulders.",
        instructions: "Move forward on hands and feet while keeping your hips low and core braced.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["shoulders", "quads"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Suitcase Carry",
        description: "A loaded carry performed with weight on one side.",
        instructions: "Hold a dumbbell at one side and walk while resisting leaning.",
        exerciseType: "strength",
        primaryMuscles: ["core"],
        secondaryMuscles: ["forearms", "shoulders"],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Plate Pinch",
        description: "A grip exercise using weight plates.",
        instructions: "Pinch plates between your fingers and thumb and hold for time.",
        exerciseType: "strength",
        primaryMuscles: ["forearms"],
        secondaryMuscles: [],
        equipment: "dumbbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Reverse Barbell Curl",
        description: "An overhand curl that emphasizes the forearms.",
        instructions: "Curl the bar upward with palms facing down, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["forearms"],
        secondaryMuscles: ["biceps"],
        equipment: "barbell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Dumbbell Reverse Curl",
        description: "An overhand dumbbell curl for forearms and biceps.",
        instructions: "Curl the dumbbells upward with palms facing down, then lower with control.",
        exerciseType: "strength",
        primaryMuscles: ["forearms"],
        secondaryMuscles: ["biceps"],
        equipment: "dumbbell",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Towel Pull-Up",
        description: "A pull-up variation that heavily challenges grip strength.",
        instructions: "Hang from towels over a bar, pull your body upward, then lower slowly.",
        exerciseType: "strength",
        primaryMuscles: ["forearms"],
        secondaryMuscles: ["back", "biceps"],
        equipment: "bodyweight",
        difficulty: "advanced",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Kettlebell Farmer Carry",
        description: "A loaded carry using kettlebells.",
        instructions: "Hold kettlebells at your sides and walk while keeping your posture tall.",
        exerciseType: "strength",
        primaryMuscles: ["forearms"],
        secondaryMuscles: ["core", "shoulders"],
        equipment: "kettlebell",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Treadmill Walk",
        description: "A low-impact cardio exercise performed on a treadmill.",
        instructions: "Walk at a steady pace while keeping an upright posture.",
        exerciseType: "cardio",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "calves"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Treadmill Run",
        description: "A running workout performed on a treadmill.",
        instructions: "Run at a controlled pace while keeping your stride relaxed.",
        exerciseType: "cardio",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "calves", "core"],
        equipment: "machine",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Rowing Machine",
        description: "A full-body cardio exercise using a rowing machine.",
        instructions: "Push with your legs, pull with your arms, then return smoothly.",
        exerciseType: "cardio",
        primaryMuscles: ["back"],
        secondaryMuscles: ["quads", "glutes", "hamstrings", "biceps", "core"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Stationary Bike",
        description: "A low-impact cycling exercise.",
        instructions: "Pedal at a steady pace while keeping your hips stable and posture controlled.",
        exerciseType: "cardio",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "calves"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Elliptical",
        description: "A low-impact cardio exercise using an elliptical machine.",
        instructions: "Move with a steady rhythm while keeping your torso tall.",
        exerciseType: "cardio",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes", "hamstrings", "calves"],
        equipment: "machine",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Burpee",
        description: "A full-body conditioning exercise.",
        instructions: "Drop into a push-up position, return to standing, and jump with control.",
        exerciseType: "cardio",
        primaryMuscles: ["core"],
        secondaryMuscles: ["chest", "shoulders", "triceps", "quads", "glutes"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Cat-Cow Stretch",
        description: "A gentle spine mobility drill.",
        instructions: "Move between rounding and arching your back while breathing slowly.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: ["back"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Hip Flexor Stretch",
        description: "A mobility exercise for the front of the hips.",
        instructions: "Kneel in a lunge position and gently shift your hips forward.",
        exerciseType: "mobility",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "World's Greatest Stretch",
        description: "A full-body mobility drill for hips, hamstrings, and upper back.",
        instructions: "Step into a deep lunge, rotate your torso, then switch sides.",
        exerciseType: "mobility",
        primaryMuscles: ["core"],
        secondaryMuscles: ["quads", "glutes", "hamstrings", "shoulders"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Couch Stretch",
        description: "A deep quad and hip flexor stretch.",
        instructions: "Place one foot behind you on a bench or wall and gently open the front of the hip.",
        exerciseType: "mobility",
        primaryMuscles: ["quads"],
        secondaryMuscles: ["glutes"],
        equipment: "bodyweight",
        difficulty: "intermediate",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Thoracic Rotation",
        description: "A mobility drill for upper back rotation.",
        instructions: "Rotate your upper back while keeping your hips stable, then switch sides.",
        exerciseType: "mobility",
        primaryMuscles: ["back"],
        secondaryMuscles: ["core", "shoulders"],
        equipment: "bodyweight",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
    {
        name: "Band Shoulder Dislocate",
        description: "A shoulder mobility drill using a band.",
        instructions: "Hold a band wide, move it overhead and behind you, then return slowly.",
        exerciseType: "mobility",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["back"],
        equipment: "band",
        difficulty: "beginner",
        videoUrl: "",
        imageUrl: "",
        isCustom: false,
        createdBy: null,
    },
];
